# Generated by Django 4.1 on 2023-02-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image_link', models.TextField()),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='API',
        ),
    ]
